name: ETL Pipeline with dataFrame in it first try

on:
  push:
    branches:

      - main

jobs:
    extract-data-job:
        runs-on: ubuntu-latest
        steps:
         - name: checkut code
           uses: actions/checkout@v2

         - name: run extract-data-job
           run: python extract.py
    transform-data-job:
        runs-on: ubuntu-latest
        steps:
         - name: checkout code
           uses: actions/checkout@v2
           
         - name: run transform-data-job
           run: python transform.py
           
    load-data-job:
        runs-on: ubuntu-latest
        steps:
         - name: checkout code
           run: actions/checkout@v2
         - name: run load-data-job
           run: python load.py  
    dataframe-job:
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v2
          - name: run dataframe-job
            run: python dataframe.py 
